begin;

create table "user" (
  "id" integer primary key generated by default as identity,
  "label" text not null,
  "username" text unique not null
);

create table "auth" (
  "id" integer primary key generated by default as identity,
  "uid" integer references "user"("id") not null,
  "method" integer not null,
  "label" text not null default '',
  "data" text not null
);

create table "site" (
  "id" integer primary key generated by default as identity,
  "lat" float not null,
  "lon" float not null,
  "label" text not null,
  "address" text not null,
  "description" text not null
);

/* postgres-specific optimized box query */

create index "site_box_gist_idx" ON "site"
  using gist (box(point(lat, lon), point(lat, lon)));

/* for box (0, 0)-(20,20), query with:
  select * from "site"
  where box(point(lat, lon), point(lat, lon)) && '(0, 0), (20, 20)'::box;
*/

commit;
