BEGIN; 

CREATE TABLE "inventory" (
    "id" integer primary key generated by default as identity, 
    "item_name" text not null, 
    "site_id" varchar references "site"("id") not null, 
    "ideal_amount" integer not null, 
    "current_amount" integer not null, 
    "critical_amount" integer not null

); 


COMMIT; 