BEGIN; 

CREATE TABLE "past_donations"(
    "id" integer primary key generated by default as identity, 
    "inventory_id" integer references "inventory" ("id") not null, 
    "user_id" integer references "user" ("id") not null, 
    "amount" integer not null, 
    "donated_at" TIMESTAMPTZ DEFAULT NOW() NOT NULL
); 


COMMIT; 